---
version: '3.8'
services:
  application:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        OS_VERSION: 12
        VERSION: 0.0.1
      labels:
        APPLICATION: ResNet
        # other labels to add later
    image: kevharv/resnet:latest
    container_name: ResNet
    depends_on:
      - database
    env_file:
      - .env.development
      - .env.local
    expose:
      - 80
      - 443
    ports:
      - 80:80
      - 443:443
    restart: on-failiure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  database:
    image: postgres:16
    container_name: ResNet_DB
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env.db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 60s  

volumes:
  db_data:
    name: Database_Volume